[project]
name = "station72"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "jinja2>=3.1.6",
    "psycopg2>=2.9.10",
    "uvicorn>=0.35.0",
]
